import 'dart:developer';

import '/controller/var.dart';
import '/view/profile/about.dart';

Map words = {
  "Back": ["Back to order list", "الرجوع الى قائمة الطلبات"],
  "SignIn": ["Sign In", "تسجيل الدخول"],
  "WBack": [
    "Welcome back! Please log in to access your account.",
    "مرحبًا بك مرة أخرى! يرجى تسجيل الدخول للوصول إلى حسابك.",
  ],
  "MobileNumber": ["Mobile Number", "رقم الهاتف المحمول"],
  "Password": ["Password", "كلمة المرور"],
  "RememberMe": ["Remember me", "تذكرنى"],
  "ForgetPassword": ["Forget Password?", "نسيت كلمة المرور؟"],
  "Login": ["Login", "تسجيل الدخول"],
  "account": ["Don't have an account?", "ليس لديك حساب؟"],
  "SignUp": ["Sign Up", "اشتراك"],
  'fillCorrectlly': [
    'please fill the fields correctlly',
    "الرجاء ملء الحقول بشكل صحيح",
  ],
  'checkInternet': [
    'check your internet connection',
    "تحقق من اتصالك بالإنترنت",
  ],
  "message1": [
    "Ready to get started? Sign up now and become part of our community!",
    "هل أنت مستعد للبدء؟ سجل الآن وكن جزءًا من مجتمعنا!",
  ],
  "FullName": ["Full Name", "الاسم الكامل"],
  "message2": [
    "you should write your name as on your ID",
    "يجب عليك كتابة اسمك كما هو موجود في بطاقة هويتك",
  ],
  "Email": ["Email", "البريد إلكتروني"],
  "InvitationCode": ["Invitation Code", "رمز الدعوة"],
  "ResetPassword": ["Reset Password", "إعادة تعيين كلمة المرور"],
  "message3": ["Enter your phone number", "أدخل رقم هاتفك"],
  "ConfirmPassword": ["Confirm Password", "تأكيد كلمة المرور"],
  "message4": ["The password does not match", "كلمة المرور غير متطابقة"],
  "Verification": ["Verification", "التحقق"],
  "message5": [
    "An OTP has been sent to your email address ",
    "تم إرسال OTP إلى عنوان بريدك الإلكتروني",
  ],
  "message6": [
    "An OTP has been sent to your phone number ",
    "تم إرسال OTP إلى رقم هاتفك",
  ],
  "Verify": ["Verify", "تحقق"],
  "Congratulations": ["Congratulations", "تهانينا"],
  "message7": [
    "Your account has been verified, If you're a merchant you should upgrade your account",
    "تم التحقق من حسابك، إذا كنت تاجرًا فيجب عليك ترقية حسابك",
  ],
  "Upgradeaccount": ["Upgrade to Merchent account", "الترقية إلى حساب التاجر"],
  "GoToMain": ["Go to Main Screen", "انتقل إلى الشاشة الرئيسية"],
  "message8": [
    "Your request has been received Successfully",
    "تم استلام طلبك بنجاح",
  ],
  "Createorder": ["Create order", "إنشاء طلب"],
  "CreateTicket": ["Create New Ticket", "إنشاء تذكرة جديدة"],
  "CreateChat": ["Create New Chat", "إنشاء دردشة جديدة"],
  "Title": ["Title", "العنوان"],
  "Myorders": ["My orders", "طلباتي"],
  "Main": ["Main", "الرئيسية"],
  "Wallet": ["Wallet", "المحفظة"],
  "More": ["More", "اخرى"],
  "Chats": ["Chats", "الدردشات"],
  "message9": [
    "your request still pending please wait until your request approved ",
    "طلبك لا يزال معلقًا، يرجى الانتظار حتى تتم الموافقة على طلبك",
  ],
  "message10": [
    "your request was rejected, contact support",
    "تم رفض طلبك، اتصل بالدعم",
  ],
  "message11": ["Welcome back to Meda,", "مرحبا بكم مرة أخرى في ميدة"],
  "Points": ["Points", "النقاط"],
  "PointsBalance": ["Points Balance", "رصيد النقاط"],
  "Categories": ["Categories", "الفئات"],
  "SeeAll": ["See All", "مشاهدة الكل"],
  "Offers": ["Offers", "العروض"],
  "LatestOrders": ["Latest Orders", "أحدث الطلبات"],
  "OffersAds": ["Offers and ads", "العروض والاعلانات"],
  "MainCategory": ["Main Category", "الفئة الرئيسية"],
  "Items": ["Items", "عناصر"],
  "Item": ["Item", "عنصر"],
  "message12": [
    "you must choose one product at least",
    "يجب عليك اختيار منتج واحد على الأقل",
  ],
  "AddItems": ["Add items to order", "اضف العناصر إلى الطلب"],
  "DeleteAll": ["Delete All", "حذف الكل"],
  "Orders": ["Orders", "الطلبات"],
  "GoCart": ["Go to cart", "اذهب إلى سلة التسوق"],
  "CancelOrder": ["Cancel order", "إلغاء الطلب"],
  "message13": [
    'Are you sure you want to delete the category and all items on it? Do you want to continue?',
    "هل أنت متأكد من أنك تريد حذف الفئة وجميع العناصر الموجودة بها؟ هل تريد الاستمرار؟",
  ],
  "Confirmation": ["Confirmation", "تأكيد"],
  "Quantity": ["Quantity", "الكمية"],
  "Label": ["Text", "النص"],
  "MembershipC": ["Membership class : Client", "فئة العضوية: العميل"],
  "MembershipMerchant": ["Membership class : Merchant", "فئة العضوية : تاجر"],
  "Upgrade": ["Upgrade", "ترقية"],
  "message14": ["your wallet Info", "معلومات المحفظة الخاصة بك"],
  "message15": [
    "View the orders list you created",
    "عرض قائمة الطلبات التي قمت بإنشائها",
  ],
  "message16": ["Review your past bills", "راجع فواتيرك السابقة"],
  "message17": ["View the banking account list", "عرض قائمة الحسابات المصرفية"],
  "message18": ["Follow your favorite companies", "تابع شركاتك المفضلة"],
  "message19": [
    "About us, Terms and conditions, Privacy policy",
    "معلومات عنا، الشروط والأحكام، سياسة الخصوصية",
  ],
  "Paid": ["Paid", "مدفوع"],
  "ExpiredNotpaid": ["Expired and not paid", "منتهي الصلاحية وغير مدفوع"],
  "Pending": ["Pending", "قيد الانتظار"],
  "message20": [
    "Change language,Enable notifications,...etc",
    "تغيير اللغة، تفعيل الإشعارات،...إلخ",
  ],
  "message21": [
    "Live chat with customer support agent",
    "الدردشة المباشرة مع وكيل دعم العملاء",
  ],
  "Help": ["Help & Support", "المساعدة والدعم"],
  "Settings": ["Settings", "الإعدادات"],
  "About": ["Policies", "السياسات"],
  "Partners": ["Our Partners", "شركاؤنا"],
  "BankingAccounts": ["Banking Accounts", "الحسابات المصرفية"],
  "MyBills": ["My Bills", "فواتيري"],
  "Logout": ["Logout", "تسجيل الخروج"],
  "Success": ["Success", "تم بنجاح"],
  "Close": ["Close", "أغلق"],
  "Dealers": ["Dealers", "التجار"],
  "ApproveSelectedOffers": [
    "Approve Selected Offers",
    "الموافقة على العروض المختارة",
  ],
  "Receivedoffers": ["Received offers", "العروض المستلمة"],
  "message22": [
    "Your offer has been submitted successfully.",
    "تم تقديم عرضك بنجاح.",
  ],
  "MedaApp": ["Meda App", "تطبيق ميدة"],
  "message23": [
    "Your order has been submitted successfully, You can check your received offers by clicking on the Orders tab",
    "تم تقديم طلبك بنجاح، يمكنك التحقق من العروض التي تلقيتها بالضغط على علامة تبويب الطلبات ",
  ],
  "Notifications": ["Notifications", "الإشعارات"],
  "message24": ["There is no data yet", "لا توجد بيانات حتى الآن"],
  "message25": ["Latest Withdrawal Requests", "أحدث طلبات السحب"],
  "message26": [
    "Successfully completed, a message with invoice details has been sent",
    "تم بنجاح، تم إرسال رسالة تحتوي على تفاصيل الفاتورة",
  ],
  "message27": ["Points | Approved", "النقاط | تمت الموافقة"],
  "message28": [
    "Successfully completed, a message with invoice details has been sent",
    "تم بنجاح، تم إرسال رسالة تحتوي على تفاصيل الفاتورة",
  ],
  "message29": ["Not delivered orders", "لم يتم تسليم الطلبات"],
  "message30": [
    'Are you sure you want to delete you account?',
    "هل أنت متأكد أنك تريد حذف حسابك؟",
  ],
  "LatestTransactions": ["Latest transactions", "أحدث المعاملات"],
  "amount": ["amount", "المبلغ"],
  "MoneyTransfer": ["Money Transfer", "تحويل الأموال"],
  "deductionAmount": ["deduction amount", "مبلغ الخصم"],
  "SadadTransactions": ["Sadad transactions", "معاملات سداد"],
  "SNumber": ["SADAD Number:", "رقم سداد:"],
  "ChargeWallet": ["Charge Wallet", "شحن المحفظة"],
  "EnterAmount": ["Enter Amount", "أدخل المبلغ"],
  "Pay": ["Pay", "دفع"],
  "AvaiablePoints": ["Available Points", "النقاط المتاحة"],
  "Avaiableorders": ["Avaiable orders", "الطلبات المتاحة"],
  "Approvedorders": ["Approved orders", "الطلبات المعتمدة"],
  "AvailableBalance": ["Available Balance", "الرصيد المتاح"],
  "WithdrawalRequests": ["Withdrawal Requests", "طلبات السحب"],
  "Request": ["Request", "طلب"],
  "Pending": ["Pending", "قيد الانتظار"],
  "Approved": ["Approved", "موافقة"],
  "Rejected": ["Rejected", "مرفوض"],
  "Support": ["Support", "الدعم"],
  "Bills": ["Bills", "الفواتير"],
  "Select All": ["Select All", "تحديد الكل"],
  "issues": ["issues", "مشاكل"],
  "suggestions": ["suggestions", "اقتراحات"],
  "DeleteAccount": ["Delete Account", "حذف الحساب"],
  "DAccount": ["Delete my account", "حذف حسابي"],
  "SettingAcc": ["Account Settings", "إعدادات الحساب"],
  "Preferences": ["Preferences", "التفضيلات"],
  "Language": ["Language", "اللغة"],
  "message31": ['Rate your experience with us!', "قم بتقييم تجربتك معنا!"],
  "message32": ["Bill Details", "تفاصيل الفاتورة"],
  "message34": ["Order Number", "رقم الطلب"],
  "message35": ["Date/Time", "التاريخ/الوقت"],
  "message33": ["Your cart is empty", "سلة التسوق الخاصة بك فارغة"],
  "message36": [
    "Looks like you have not added anything to your cart. Go ahead & explore categories",
    "يبدو أنك لم تقم بإضافة أي شيء إلى سلة التسوق الخاصة بك. يمكنك المضي قدمًا واستكشاف الفئات",
  ],
  "message37": [
    "Error while detect the address please give the required permission",
    "حدث خطأ أثناء اكتشاف العنوان، يرجى إعطاء الإذن المطلوب",
  ],
  "User": ["User", "المستخدم"],
  "Merchant": ["Merchant", "التاجر"],
  "balanceDeduction": ["balance after deduction", "الرصيد بعد الخصم"],
  "walletbalance": ["wallet balance", "رصيد المحفظة"],
  "Paywallet": ["Pay from your wallet", "الدفع من المحفظة"],
  "Paywithmoyasar": ["Pay with mada/visa", "الدفع بواسطة البطاقة (مدى/فيزا)"],
  "SR": ["SR", "ريال"],
  "points": ["points", "نقاط"],
  "review": ["Review", "مراجعة"],
  "Submit": ["Submit", "إرسال"],
  "Yes": ["Yes", "نعم"],
  "No": ["No", "لا"],
  "VatNumber": ["Vat Number", "رقم ضريبة القيمة المضافة"],
  "VAT": ["VAT", "ضريبة القيمة المضافة"],
  "Firmname": ["Firm name", "اسم الشركة"],
  "TotalPrice": ["Total Price", "السعر الاجمالي"],
  "Cart": ["Cart", "العربة"],
  "Continue": ["Continue", "إستمرار"],
  "ContinuePayment": ["Continue to Payment", "المتابعة للدفع"],
  "Selectpay": ["Select bills you want to pay", "حدد الفواتير التي تريد دفعها"],
  "Totalamount": ["Total amount", "المبلغ الإجمالي"],
  "Cancel": ["Cancel", "إلغاء"],
  "Add": ["Add", "إضافة"],
  "Paynow": ["Pay now", "ادفع الآن"],
  "UpdateBankAccount": ["Add/Update Bank Account", "إضافة/تحديث حساب بنكي"],
  "BankName": ["Bank Name", "اسم البنك"],
  "IBAN": ["IBAN", "رقم الآيبان"],
  'OK': ['OK', 'نعم'],
  'OK2': ['OK', 'حسنا'],
  'opened': ['opened', 'فتح'],
  'message100': [
    'Your balance is not enough for this transaction. Please payment through moyasar and continue.',
    'رصيدك غير كافي لهذه العملية يرجى اختيار طريقة الدفع المناسبة والاستمرار',
  ],
  "Deduction": ["Deduction", "خصم"],
  "IncomingTransaction": ["Incoming Transaction", "معاملة واردة"],
  "Checkout": ["Checkout", "الدفع"],
  "message40": [
    "You should agree the terms and conditions before continue",
    "يجب عليك الموافقة على الشروط والأحكام قبل الاستمرار",
  ],
  "message41": ["  I agree to", " أوافق على"],
  "message42": [" Terms and Conditions", " الشروط والأحكام"],
  "message43": ["Pay with MEDA points", "الدفع باستخدام نقاط MEDA"],
  "message44": ["Pay with points balance", "الدفع باستخدام رصيد النقاط"],
  "Sitelocation": ["Site location", "موقع الموقع"],
  "ChangeLocation": ["Change Location ", "تغيير الموقع"],
  "Payment": ["Payment", "الدفع"],
  "pointbalance": ["point balance", "رصيد النقاط"],
  "OrderFees": ["Order Fees", "رسوم الطلب"],
  "message38": ["Choose Document", "اختر المستند"],
  "message39": [
    "Select original files up to 500 MB in size.",
    "حدد الملفات الأصلية التي يصل حجمها إلى 500 ميجا بايت.",
  ],
  "message51": ["you should choose pdf file ", "يجب عليك اختيار ملف pdf"],
  "message52": ["Choose from Files", "اختر من الملفات"],
  "message53": [
    'Only PNG and JPEG and gif images are allowed',
    'يُسمح فقط بالصور بتنسيق PNG وJPEG وgif',
  ],
  "message54": ["Choose from Photos", "اختر من الصور"],
  "message55": ["Microphone permission is required", "مطلوب إذن الميكروفون"],
  "message56": [
    'Recording stopped, but path is null',
    'تم إيقاف التسجيل، لكن المسار فارغ',
  ],
  "message57": ["please enter message text", "الرجاء إدخال نص الرسالة"],
  "PdfFil": ["Pdf File", "ملف PDF"],
  "Orderdate": ["Order date", "تاريخ الطلب"],
  "Status": ["Status", "الحالة"],
  "AboutMeda": ["About Meda", "عن ميدة"],
  "UpgradeAccount": ["Upgrade Account", "ترقية الحساب"],
  'NationalID': ['National Identification ID', 'بطاقة الهوية الوطنية'],
  'VNumber': ['Vat registeration Number', 'رقم تسجيل ضريبي'],
  'Commercialregister': ['Commercial register', 'السجل التجاري'],
  "File": ["File", "ملف"],
  "Photo": ["Photo", "صورة"],
  "Audio": ["Audio", "صوت"],
  "Location": ["Location", "الموقع"],
  "BestSellers": ["Products in your store", "منتجات في متجرك"],
  "message49": ["Holes steamed concrete blocks", "ثقوب كتل الخرسانة المبخرة"],
  "SelectCity": ["Select City", "اختر المدينة"],
  "SubmitOffer": ["Submit your offer", "أرسل عرضك"],
  "Summary": ["Summary", "ملخص"],
  "withVAt": ["with VAt:", "مع ضريبة:"],
  "Store": ["Store", "المتجر"],
  "DiscountOffers": ["Discount & Offers", "الخصومات والعروض"],
  "Persent": ["Persent", "النسبة"],
  "Orderdetails": ["Order details", "تفاصيل الطلب"],
  "message58": [
    "Manage offers on your products at a discounted rate",
    "إدارة العروض على منتجاتك بأسعار مخفضة",
  ],
  "message59": ["Discount Type", "نوع الخصم"],
  "message60": ["Applied On :", "تم التطبيق في :"],
  "message61": ["Whole Store", "المتجر بالكامل"],
  "message62": ["Specific Items", "عناصر محددة"],
  "message63": ["Apply Discount", "تطبيق الخصم"],
  "message64": ["Edit product price", "تعديل سعر المنتج"],
  "message65": ["new price", "السعر الجديد"],
  "message66": ["Discount applied on all items", "خصم على جميع العناصر"],
  "message67": [
    "Discount applied on selected items",
    "تم تطبيق الخصم على العناصر المحددة",
  ],
  "message68": [
    "Enable discount on store items",
    "تفعيل الخصم على العناصر الموجودة بالمتجر",
  ],
  "Value": ["Value", "القيمة"],
  "Edit": ["Edit", "تعديل"],
  "Apply": ["Apply", "تنفيذ"],
  "MainCategories": ["Main Categories", "الفئات الرئيسية"],
  "SubCategories": ["Sub Categories", "الفئات الفرعية"],
  "Managetore": ["Manage your store", "إدارة متجرك"],
  "All": ["All", "الجميع"],
  "Price": ["Price", "السعر"],
  "Delete": ["Delete", "حذف"],
  "OrderNo": ["Order No#", "رقم الطلب#"],
  "comReg": ["Commercial register :", "السجل التجاري :"],
  "UnitPrice": ["Unit Price", "سعر الوحدة"],
};
String getText(String key) {
  String t = "";
  try {
    if (language == "0") {
      t = words[key][0];
    } else {
      t = words[key][1];
    }
  } catch (e) {
    log(key);
  }
  return t;
}
